name: my first workflow

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Executing shell scriipt
        run: ./ascii-scriipt.sh

      - name: List Repo files
        run: ls - ltra
